<?php
  include 'codelink.php';
  $program='python test.py';

  $dataname='forminfo';
  $data="Welcome to Drone Town doubles city";
  $dataname2='puredata';
  $data2='2+1';
 $result=codelink_pass($program,$dataname,$data);
 echo $result;
  // $result=array();
  // array_push($result, codelink_pass($program,$dataname,$data));
 # array_push($result, codelink_pass($program,$dataname2,$data2));
 // array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));array_push($result, codelink_pass($program,$dataname,$data));
 // array_push($result, codelink_pass($program,$dataname2,$data2));
 // var_dump(codelink_pass($program,$dataname,$data));
 // var_dump(codelink_pass($program,$dataname2,$data2));

 //var_dump($result);
?>